files_in = '/home/gonzalo/data/NEXT/esmeralda/hdst_7050_trigger2.h5'
file_out = 'crap.h5'
compression = 'ZLIB4'
event_range = 1000
# run number 0 is for MC
run_number = 7002
# How frequently to print events
print_mod = 1
cor_hits_params             = dict(
  map_fname                 = '$ICDIR/database/test_data/kr_emap_xy_100_100_r_6573_time.h5',
  threshold_charge_reco     = 6  * pes,
  threshold_charge_paolina  = 30  * pes,
  same_peak                 = True,
  apply_temp                = True)
  
paolina_params      = dict(
   vox_size         = [15 * mm, 15 * mm, 15 * mm],
   strict_vox_size  = True,
   energy_threshold = 20 * keV,
   min_voxels       = 2,
   blob_radius      = 21 * mm)
